HadoukenIO/layouts-service

- src/SnapAndDock/Client/main.ts
fixes the keyboard shortcut on windows #2
> Shortcut fix

- src/SnapAndDock/Service/listeners.ts
Needed to bind an Application method.
> RUN-4116 fixed the issue where main window registration was sometimes failing

- scripts/dev.js
OpenFin was sometimes launching before build was completed.
> fixed a timing bug in dev script

- src/SnapAndDock/Service/SnapPreview.ts
> Change SnapPreview to use about:blank instead of blank html file

- example/package.json
- package-lock.json
- src/Layouts/Service/restore.ts
Version 6 may have a security vulnerability.
> Bump serve version.

- webpack.config.js
Was causing build to fail when running on Jenkins.
> Fixed case sensitivity issue within webpack config

- src/client/main.ts
- src/demo/Snappable.ts
- src/provider/main.ts
- test/provider/utils/explodeGroup.ts
- test/provider/utils/undockWindow.ts
Updated the undock and explode methods to match the new spec. All other S&D api methods are already compliant.
> [SERVICE-222] Update SnapAndDock api to match new spec

- res/demo/app3.json
- res/demo/tabbing/app.json
> fix runtime version regression

- src/provider/tabbing/DragWindowManager.ts
- src/provider/tabbing/TabAPIActionProcessor.ts
- src/provider/tabbing/TabGroup.ts
- src/provider/tabbing/TabService.ts
- src/provider/tabbing/TabWindow.ts
- src/provider/tabbing/asyncWindow.ts
Reworks hidden window logic to make the windows truly hidden instead of using opacity: 0
> [SERVICE-223] Rework Hidden Windows Logic

- src/fin.d.ts
- src/provider/snapanddock/SnapService.ts
Fix a bug where new windows would occasionally not be registered with the service.
> [SERVICE-228] Certain windows will occasionally fail to register with the S&D service

- src/provider/tabbing/components/ApplicationConfigManager.ts
- test/demo/tabbing/createTabFromMultipleWindows.test.ts
- test/provider/tabOnDragOver.test.ts
Updated tests to reflect behaviour changes with tabbing. Two of three failing tests fixed, one is failing genuinely. Test marked as failing to unblock CI, will be fixed as part of workspaces/tabbing integration work.
> Test fixes

- src/fin.d.ts
- src/provider/snapanddock/SnapService.ts
- src/provider/snapanddock/SnapWindow.ts
Fix window opacity changing when dragging deregistered windows
> [SERVICE-213] Deregistered windows still have opacity effect applied when being dragged

- src/client/main.ts
- src/client/types.ts
- src/demo/LayoutsUI.ts
- src/provider/workspaces/create.ts
We want users to only be able to add customData to a Layout, not change the layout information on the fly.
> [SERVICE-229] Change onWillSaveAppLayout to only pass customData back

- src/provider/snapanddock/SnapPreview.ts
Fix for preview window getting stuck showing intermittently
> [SERVICE-235] Preview windows gets stuck intermittently

- src/provider/tabbing/GroupWindow.ts
* Adds Xaviers work around for blank windows
* Removes wait on tab strip showing
> Blank Window Fix

- src/provider/snapanddock/Config.ts
- src/provider/snapanddock/SnapPreview.ts
Slight changes snap and dock UX to address usability concerns.
> Slight UX Tweaks to S&D

- src/provider/tabbing/GroupWindow.ts
- src/provider/tabbing/Tab.ts
- src/provider/tabbing/TabGroup.ts
- src/provider/tabbing/TabService.ts
- src/provider/tabbing/TabWindow.ts
Fixes some maximize + tabbing logic
> [SERVICE-239] Maximized Windows + Tabbing Improvements

- res/demo/tabbing/UI/UI1.html
- res/demo/tabbing/UI/UI2.html
> Fix Custom UI

- src/provider/snapanddock/SnapWindow.ts
Added onFocused listener to each SnapWindow which will bring all other windows in it's group to front
> [SERVICE-241] Bring all other windows in group to front when snapped window is focused

- res/demo/LayoutsUI.html
- src/demo/LayoutsUI.ts
Adds a close all windows button to the demo UI
> Add Close All Windows Demo Button

- src/provider/snapanddock/SnapService.ts
- src/provider/tabbing/TabUtilities.ts
Fixes the 'feature' to tab to a minimized window.
> [SERVICE-250] Can tab to minimised windows

- package-lock.json
- src/demo/LayoutsUI.ts
- src/provider/tabbing/TabUtilities.ts
- src/provider/workspaces/restore.ts
- src/provider/workspaces/utils.ts
- Places windows in their proper locations before showing them. 
- Refactoring, updating, moving of code to be more organized.
> Pre-cut for 249.

- package.json
> Bumping version to 0.9.2

- package.json
> Bumping version to 0.9.3

- package-lock.json
- package.json
Updates packages to remove any known vulnerabilities flagged by `npm audit`.  Breaking changes possible, please test thoroughly before merging!
> [SERVICE-261] Upgrade Webpack to remove vulnerable dependency

- src/provider/tabbing/TabGroup.ts
- test/provider/tabOnDragOver.test.ts
Adds 'TABSET-' as a prefix to the name of all tab set windows.  Format name will be `TABSET-{uuidv4}`
> Adds Additional Tests for Tabbing

- src/provider/model/DesktopTabGroup.ts
- src/provider/model/DesktopTabGroupWindowFactory.ts
- src/provider/tabbing/components/ApplicationConfigManager.ts
Adds window pooling for tab strip windows.
> [SERVICE-240] Speedup Tab Window Timing

- src/provider/model/DesktopWindow.ts
- src/provider/tabbing/TabService.ts
- test/provider/tabOnDragOver.test.ts
- test/provider/utils/tabWindowsTogether.ts
Fixed failing tests due to service provider hanging whilst sending message to window. Added some missing awaits, removed a potentially problematic async util.
> Fixed failing tabbing tests

- package-lock.json
- src/demo/LayoutsUI.ts
- src/demo/normalApp.ts
- src/demo/storage.ts
- src/demo/tabapp1.ts
- src/demo/tabapp2.ts
- src/provider/Signal.ts
- src/provider/model/DesktopModel.ts
- src/provider/model/DesktopTabGroup.ts
- src/provider/tabbing/TabService.ts
- src/provider/workspaces/create.ts
- src/provider/workspaces/group.ts
- src/provider/workspaces/restore.ts
- src/provider/workspaces/utils.ts
- Fix deregister bug in demo windows
- Properly restore child windows and tabbed windows
- Properly reassign the active tab in a tabset when restoring
> Save And Restore Update

- src/provider/model/DesktopModel.ts
- src/provider/model/DesktopSnapGroup.ts
- src/provider/model/DesktopWindow.ts
- src/provider/snapanddock/SnapService.ts
- test/demo/snapanddock/basicSnapAndDock.test.ts
- test/demo/snapanddock/resizeOnSnap.test.ts
- test/demo/snapanddock/validateGroup.test.ts
- test/demo/utils/createWindowTest.ts
- test/demo/utils/snapServiceUtils.ts
- test/provider/utils/WindowInitializer.ts
- test/provider/utils/assertions.ts
- test/provider/utils/isContiguousGroup.ts
Added implementation for validate group function. Will now split the group if it becomes disjoint.
> [SERVICE-130] SnapGroup Validation

- test/demo/snapanddock/basicSnapAndDock.test.ts
- test/demo/snapanddock/resizeSnapGroup.test.ts
- test/demo/snapanddock/validateGroup.test.ts
- test/provider/explodeGroup.test.ts
- test/provider/utils/WindowInitializer.ts
Some tests were consistently failing only when run in CI. Made some tweaks to resolve.
Need to leave this PR and ensure that it builds properly in CI.
> Fix breaking tests

- README.md
- res/demo/app.json
- res/demo/app2.json
- res/demo/app3.json
- res/demo/tabbing/app.json
- res/provider/app.json
- res/test/app.json
- res/test/provider.json
This should be the stable version of 9.61.36.x very soon. Need to get this build into staging to validate before release.
> Bump to runtime 9.61.36.36

- package.json
> Bumping version to 0.9.4

- res/provider/app.json
Adds an openfin license key and removes the  remote logging configuration
> [SERVICE-273] Service App.json update - remove remote logging and update license key

- Jenkinsfile
- package.json
- scripts/createProviderZip.js
- Added script that generates a zip of the provider files required to run a hosted instance of the service. 
- Updated jenkinsfile to run the new script before deploying to aws (prod or staging)
> [SERVICE-254] Package the service for hosted deployment

- src/provider/tabbing/TabService.ts
Fixed bug where snapped windows could be tabbed with other windows/groups.
> [SERVICE-200] Can dock snapped window bugfix

- package.json
> Bumping version to 0.9.5

- webpack.config.js
Client was being packaged without exports. Changed Webpack to build it as a UMD module.
> Fix no exports in layouts client

- package.json
> Bumping version to 0.9.6

- package-lock.json
- test/demo/utils/AppInitializer.ts
- test/demo/utils/serviceUtils.ts
- test/demo/utils/workspacesUtils.ts
- test/demo/workspaces/basicSaveAndRestore.test.ts
- test/demo/workspaces/deregisteredBasicSaveAndRestore.test.ts
- test/demo/workspaces/snapSaveAndRestore.test.ts
- test/demo/workspaces/tabSaveAndRestore.test.ts
- test/runner.js
- Adds S&R testing for applications created from a manifest
- Adds S&R testing for deregistered applications
- Removes tests with 3 children to save time and limit likelihood of tests failing for windows off-screen
> [SERVICE-282] Add additional test coverage to Save and Restore

- src/provider/tabbing/components/ApplicationConfigManager.ts
- test/demo/tabbing/createTabFromMultipleWindows.test.ts
Fix error from erroneously removed import
Fix error from dependency on  window.location.href being indirectly introduced via inclusion of ApplicationConfigManager.DEFAULT_UI_URL
> [N/A] Fix failures in createTabFromMultipleWindows

- test/teardown.ts
Currently adding unnecessary delay to test runs
> [N/A] Reducing the delay period within teardown util

- src/client/tabbing.ts
- src/client/tabstrip.ts
- src/provider/APIHandler.ts
- src/provider/model/DesktopTabstripFactory.ts
- src/provider/tabbing/TabService.ts
- test/client/TabApi.unittest.ts
- test/client/TabGroupActions.unittest.ts
- test/client/TabStripApi.unittest.ts
- test/client/utils/ErrorMsgs.ts
Misc bugfixes from integrating different 0.9.6 stories.
See commit messages for details.
> [N/A] 0.9.6 integration fixes

- package.json
> Bumping version to 1.0.0

- src/provider/model/DesktopTabGroup.ts
- src/provider/model/DesktopTabstripFactory.ts
- src/provider/model/DesktopWindow.ts
For 1.0: Hides the tabset window on the taskbar, instead shows the active tab.
> [SERVICE-315] Layouts Taskbar Management issues

- test/client/TabStripApi.unittest.ts
Fixes unit tests caused by the earlier API updates
> [N/A] Unit Tests

- src/provider/snapanddock/Projector.ts
> [SERVICE-361] Certain configurations of snapped windows will allow you to snap a new window partially on top of other windows.

- src/client/workspaces.ts
Add more instructions to avoid gotchas.
> Update description for setRestoreHandler

- package.json
> Bumping version to 1.0.1

- res/demo/app.json
- res/demo/app2.json
- res/demo/app3.json
- res/test/app.json
- res/test/deregisteredApp1.json
- res/test/deregisteredApp2.json
- res/test/provider.json
- res/test/registeredApp1.json
- res/test/registeredApp2.json
- scripts/server/spawn.js
Adds the services license key to all layouts app.json files, as well as the app.json middleware.
> [SERVICE-411] Add OpenFin Licence key to all service windows

- src/demo/spawn.ts
- src/provider/model/DesktopWindow.ts
> [N/A] Ensure that apps spawned during tests are on the same runtime as the parent test app

- src/provider/tabbing/TabService.ts
We initially had it so that a when saving a workspace containing the default tabstrip, that tabstrip would be saved using the string 'default', rather than the full details of the tabstrip. This broke at some point, and this fixes that
> [N/A] Fix default tabstrips being saved using their full URL rather than 'default'

- package-lock.json
- src/client/connection.ts
- test/client/TabApi.unittest.ts
- test/client/TabGroupActions.unittest.ts
- test/client/TabStripApi.unittest.ts
Fixes the client/connection.ts error prevalent in the demo
```
channelPromise is undefined
```
> [NA] Fix Client Connection

- src/provider/model/ZIndexer.ts
ZIndexer used to rely on timestamp to order its entities. If two events arrive in the same millisecond, this could give unexpected results. This was sometimes visible with `tabToMaximizedWindow.test.ts`, which did the following:
```
await windows[2].setAsForeground();
await windows[1].setAsForeground();
await windows[0].setAsForeground();
```
which when relying on timestamp, may not give the expected results, giving a random, performance dependent, test failure. This PR changes `ZIndexer` to use a counter rather than timestamp
@pjbroadbent, @MichaelMCoates - Know you've already taken a look at this, but had to recreate due to merge hell, due to me being 'clever'
> [N/A] ZIndexer fix

- package.json
> Bumping version to 1.0.2

- README.md
Removes references to server.js
> [NA] Update README.md

- res/provider/config/layouts-config.schema.json
- src/client/main.ts
- src/finV2.d.ts
- src/provider/model/DesktopModel.ts
- src/provider/model/DesktopWindow.ts
- src/provider/model/ZIndexer.ts
- src/provider/snapanddock/Projector.ts
- src/provider/snapanddock/Resolver.ts
- src/provider/utils/main.ts
This adds ability for an external window (only Notepad for now) to snap, and unsnap. This also shows potential targets while moving.
> RUN-5108 adds ability for external windows to snap

- package.json
> Bumping version to 1.0.3

- README.md
Fixed broken link, some minor whitespace/wording changes.
> [N/A] Updated README

- package.json
> Bumping version to 1.0.4

- package-lock.json
- package.json
> Bumping version to 1.0.5

- package-lock.json
- package.json
> Bumping version to 1.0.6

- README.md
- res/demo/app.json
- res/demo/app2.json
- res/demo/app3.json
- res/demo/testbed/index.html
- res/provider/app.json
- res/test/deregisteredApp1.json
- res/test/deregisteredApp2.json
- res/test/provider.json
- res/test/registeredApp1.json
- res/test/registeredApp2.json
- res/test/test-app-main.json
- src/provider/model/DesktopWindow.ts
- test/demo/monitorChange.inttest.ts
- test/demo/tabbing/previewOpacityTab.inttest.ts
- test/demo/tabbing/tabGroupResizeConstraints.inttest.ts
- test/demo/tabbing/tabToMaximizedWindow.inttest.ts
> Staging test

- README.md
For ease of following feedback, please can any cross-project feedback go in - https://github.com/HadoukenIO/notifications-service/pull/115
> [SERVICE-584] Refresh Service READMEs

- README.md
- res/demo/app.json
- res/demo/app2.json
- res/demo/app3.json
- res/demo/testbed/index.html
- res/provider/app.json
- res/test/deregisteredApp1.json
- res/test/deregisteredApp2.json
- res/test/provider.json
- res/test/registeredApp1.json
- res/test/registeredApp2.json
- res/test/test-app-main.json
- src/provider/model/DesktopWindow.ts
13.76.43.32 has a rendering patch that we would want as part of the soft landing upgrade to 13
> Upgrade runtime to 13.76.43.32
