HadoukenIO/layouts-service

CONTRIBUTING.md

Initial contributing guide.
FinOS will have a digital CLA solution we can add.
Should we include a link to the HadoukenIO slack?

Initial Contributing guide

---

src/SnapAndDock/Service/SnapPreview.ts

Really just a config change, the green causes awkward flashes in certain positions, and considering doing just a color change isn't accessibility friendly, having a single color looks better in demos.

Change the preview color to only show success.

---

src/demo/LayoutsUI.ts

Issue reported where saving and restoring the frameless snappable windows from the demo does not maintain the framelessness of the windows.

Fix demo windows not persisting frames on restore

---

src/provider/snapanddock/Resolver.ts
src/provider/tabbing/TabUtilities.ts
src/provider/tabbing/TabWindow.ts
src/provider/tabbing/components/ApplicationConfigManager.ts

These features are not yet integrated, which is causing usability issues. This PR filters snapping and tabbing actions until we can complete SERVICE-200.
PR also contains a change to what happens when removing a window from a tab set. `TabWindow` will now only restore the frame of a window if the window had a frame before it was tabbed.

[SERVICE-230] Disabled snapping for tab sets, and tabbing of snapped windows

---

src/provider/tabbing/GroupWindow.ts

Service provider now determines URL of the default tabstrip based on it's own URL. Should ensure default tab strip location is correctly determined when running from CDN as well as locally.

Fixed default tab strip URL

---

res/demo/app2.json
res/demo/app3.json
res/provider/app.json
res/test/provider.json
src/client/main.ts
src/client/types.ts
test/client/TabbingApi.unittest.ts
test/client/TabbingApiWindowActions.unittest.ts
test/demo/tabbing/createTabFromMultipleWindows.test.ts
test/demo/utils/executeJavascriptOnService.ts
test/provider/deregisterWindow.test.ts
test/provider/previewWindow.test.ts
test/provider/utils/explodeGroup.ts
test/provider/utils/undockWindow.ts

NOTE: This change will require client and provider to be updated in tandem. Any client versions from prior to this change will not work with provider versions from after it, and vice versa.
Change service UUID from 'Layouts-Manager' to 'layouts-service'

[SERVICE-234] Update service app UUID to something more descriptive

---

src/provider/snapanddock/SnapGroup.ts

SnapGroup wouldn't know to refresh it's internal state when a layout is restored. Will now mark it's cache as stale when a window within the group is modified.
This may end up being slightly excessive. Should find a way to better detect restore events as part of future refactoring.

Fixed occasional incorrect preview windows when restoring a layout

---

package-lock.json
package.json
src/client/main.ts
src/provider/main.ts
src/provider/snapanddock/SnapService.ts

Provider now registers a global listener for `CommandOrControl+Shift+U` which will undock the currently focused window if possible. Also removed the old hotkey listener from the client.
This will mean that all windows controlled by the service, regardless of runtime or client import, will be undockable.

Move hotkey from client to global registration in provider

---

res/demo/app2.html
res/demo/app3.html
res/demo/app4.html
res/demo/app5.html
res/demo/demo-window.html
src/demo/deregisteredApp.ts
src/demo/normalApp.ts
src/provider/main.ts
src/provider/workspaces/create.ts
src/provider/workspaces/restore.ts
src/provider/workspaces/utils.ts
webpack.config.js

Deregister now deregisters a window from Save & Restore as well. If an application is deregistered, its child windows will not Save & Restore, even if they aren't deregistered.
- Implement deregister for normal windows
- Handle edge cases when restoring tab groups with a combination of valid windows and child windows of deregistered windows
- Separate LayoutsUI code from demo application/demo window code
- Refactor window object manipulation to a few util functions.

[SERVICE-253] Deregister for Save & Restore

---

src/provider/tabbing/TabUtilities.ts
src/provider/tabbing/TabWindow.ts

Tab strip + apps are no longer split when you eject a tab

[SERVICE-252] z-ordering - when dragging tabs out of tabset

---

src/fin.d.ts
src/provider/snapanddock/SnapService.ts

Seems maybe there was a merge conflict that wasn't resolved properly, global hotkeys was using a weird mix of v1 and v2 API's.
Fixed implementation to use V1 API, updated .d.ts accordingly.

Fixed issue in global hotkeys

---

Jenkinsfile

Moved document generation to after the build within Jenkinsfile. Otherwise docs step fails due to code referencing a file that is generated during the build process.

Fixed build failure during tsdoc generation

---

src/provider/snapanddock/SnapService.ts

Ignore undock global hotkey event for windows in tabsets until tab/snap is fully integrated.

[SERVICE-269] Tabbed window detaches from tabstrip when global undock hotkey is pressed

---

src/provider/workspaces/restore.ts

I originally moved some app.mainWindow positioning logic over to the placeholder window. However, this introduced a timing issue when trying to restore a layout with only main window apps. I have added back the positioning logic.

Fix app snapping timing bug

---

src/provider/model/DesktopTabGroup.ts

UX improvement to change the tab placeholders from `Placeholder-[random alphanumeric characters]` to something more user friendly. 
Went with `Loading...` for a first attempt and looks pretty good in my opinion. Open to other suggestions. Image of what it looks like is below.

[SERVICE-271] Make S&R placeholder tab titles more user-friendly

---

res/demo/LayoutsUI.html
res/demo/tabbing/App/DisableFrame.html
src/provider/Signal.ts
src/provider/main.ts
src/provider/model/DesktopModel.ts
src/provider/model/DesktopWindow.ts
src/provider/model/MouseTracker.ts

Added additional option to support environments where the Windows "Show window contents while dragging" performance option is disabled.
Fix works by calling `disableFrame()` for all windows managed by the service, and then managing the movement/resizing of windows programatically. This works since these events are still dispatched as normal when running in this mode, whereas normal `bounds-changing` events are not.
The `disableFrame()` call is not made immediately, as the service must support windows that are using this method within the application itself. The service will wait a short time before checking if the window has enabled `disableFrame()` behaviour. Have added an extra button to the demo app that creates an app window that uses `disableFrame()`. De-registering a window from the …

[SERVICE-266] Added support for virtualised environments

---

src/provider/snapanddock/SnapService.ts

Hotfix for 0.9.3 to make group validation less strict.
Will merge back into develop in subsequent PR.

0.9.3 Hotfix

---

res/test/crash.html
src/provider/model/DesktopModel.ts
test/provider/ignoreErrorWindows.test.ts

Added checks when registering windows to ensure the service ignores any windows with uuid/name matching the pattern `error-app-{UUIDv4}`.

[SERVICE-270] Exclude OpenFin error dialogs from the service

---

src/client/APITypes.ts
src/client/main.ts
src/client/types.ts
src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts
src/provider/tabbing/tabstrip/main.ts
test/demo/utils/tabServiceUtils.ts
test/provider/updateTabProperties.test.ts

This PR adds an event listener `tab-properties-updated` which will receive events when the API method `updateTabProperties` is used.  This will resolve the issue previously noted for the tab strip not updating correctly when the API method was called externally.

[SERVICE-274] Tab title in tabstrip UI doesn't update if a tab is renamed by an application

---

res/test/testApp.js

Issue with calling generateLayout. Fixed by registering onAppSave and onAppRestore callbacks on the testApp.
Currently causing tests in CI to hang intermittently.

Fix hanging tests

---

src/fin.d.ts
src/provider/model/DesktopSnapGroup.ts
src/provider/model/DesktopWindow.ts
src/provider/snapanddock/Projector.ts
test/demo/snapanddock/resizeOnSnap.test.ts
test/demo/utils/modelUtils.ts

Summary of changes: 
- Updated the model's windowState interface to include resizable and resizeRegion.
- Added public method on DesktopWindow to allow getting constraints data in a more manageable format.
- Added checks to projector that block resizing if it would violate these constraints, or min/max height/width.

[SERIVCE-135] Respect window size constraints when snapping

---

src/provider/snapanddock/Projector.ts
test/demo/snapanddock/advancedSnapAndDock.test.ts
test/provider/utils/assertions.ts
test/provider/utils/isOverlappedWith.ts

Adjusted the projector logic so it now includes windows within the anchor distance when determining new bounds. 
Note: the distance at which a window is snapped has not changed, just the windows we consider when doing overlap checks.

[SERVICE-220] Fix bug where grouped windows could overlap when snapping to anchor points.

---

test/runner.js

Usage: 
`npm test -- --runtime-version aa.bb.cc.dd`
Argument is injected directly into the manifest, so any valid version string should work.

[SERVICE-294] Add ability to specify runtime version when running tests

---

src/client/types.ts
src/provider/workspaces/create.ts
src/provider/workspaces/restore.ts
src/provider/workspaces/utils.ts
test/demo/worspaces/schemaVersion.test.ts

Added versioning to layout objects generated by the service. 
When `restoreLayout` is called, the version in the provided object is checked against a hard-coded version in `create.ts` (separate to the service version) and will error if they are not compatible.

[SERVICE-286] Add layout schema versioning

---

README.md
res/demo/app.json
res/demo/app2.json
res/demo/app3.json
res/provider/app.json
res/test/app.json
res/test/deregisteredApp1.json
res/test/deregisteredApp2.json
res/test/provider.json
res/test/registeredApp1.json
res/test/registeredApp2.json
src/provider/main.ts
src/provider/model/DesktopWindow.ts
src/provider/snapanddock/SnapService.ts
test/demo/snapanddock/resizeSnapGroup.test.ts
test/demo/tabbing/createTabFromMultipleWindows.test.ts
test/provider/nativeGroupListeners.test.ts
test/provider/tabOnDragOver.test.ts
test/provider/updateTabProperties.test.ts
test/provider/userBoundsChanging.test.ts

Runtime 37 contains a root-cause fix for the issue that the emulateDragEvents mode was added to work-around - and this workaround now causes issues within the service, even when disabled.
This PR simultaneously upgrades to the latest runtime version, and removes the previous work-around.
Note: The runtime used here is still pre-stable, so there may be further updates to come. Doing the upgrade now to prevent further blockers.

[SERVICE-300] Upgrade to runtime 37, remove 'emulateDragEvents' mode

---

scripts/createProviderZip.js

Bad glob pattern was resulting in two different app.json files in the self-hosting zip.

Fix double app.json in zip output

---

package-lock.json
package.json
res/config-schema/common.schema.json
res/config-schema/layouts-config.schema.json
res/config-schema/rule.schema.json
res/config-schema/scope.schema.json

Initial attempt at a config schema built from Phil's POC/prototype work.
Run `npm run generate` to create the output .d.ts files. They are currently put in `/dist/config-schema`, but that is up for discussion.

[SERVICE-289] Add config schema

---

Jenkinsfile
README.md
res/demo/LayoutsUI.html
res/demo/libScriptIncluded.html
src/demo/LayoutsUI.ts
webpack.config.js

**Do Not Merge Yet**  Pending API changes
Creates a minified client library which can be included via `script` tag.  The location will be on the CDN as `https://cdn.openfin.co/services/openfin/layouts/<VERSION>/openfin-layouts.js`.  Once included, the library will be accessible via global var `OpenFinLayouts`.  This can be tested in the demo app using 'Client Lib Included' button.

[SERVICE-299] Publish a version of the client that can be imported directly from the browser

---

test/teardown.ts

Modifying teardown util from #229 to not fail test when windows/model state is left-over after a test. Currently makes tests too brittle.
Will investigate the race conditions that happen during test teardown in the future, see if it is possible to have the service cleanly handle those edge cases.

[SERVICE-313] Modifying tear-down util to not fail test

---

package-lock.json
src/provider/workspaces/create.ts
src/provider/workspaces/utils.ts
test/demo/workspaces/formerTabGroupRestoreResize.test.ts

- Previously, if a window was a part of a tab group that was going to be disbanded (say, if it is tabbed to the child window of a deregistered App), that window would restore at a smaller size. 
- Now, windows restore at their proper size.

[SERVICE-302] Properly restore windows that were formerly a part of a tab group.

---

src/provider/model/DesktopWindow.ts

Sometimes when a snapped window is maximized, other members of the snap group will appear on top of the maximized window. Fix this by ignoring maximized windows (or windows that are part of a maximized tab group) when handling a window gaining focus.

[SERVICE-309] When a snapped window is maximised, other windows in the group can appear on top of it

---

src/provider/model/DesktopModel.ts
src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts

On `monitor-info-change` event we now globally validate all tab- and snapGroups.
SnapGroups are validated with the same logic as in other places: group is split into any remaining contiguous sets of windows.
For tabGroups, monitor resizes generally result in all state being correct with the exception of the tabstrip. When validating we check the relative position of the tabStrip to the group and move it back into position.
Note Re: testing - I discussed with Phil and we think that it would be unwise to automate screen resizing on the test slaves with the current setup. For the time being this will need to be tested manually.

[SERVICE-308] Validate desktop after monitor resolution change

---

src/provider/Preview.ts

This changes the internals of Preview to use two separate windows for success and failure, rather than changing CSS, which seems to take a frame to update, causing the flicker.
This also removes leftover debugging functionality, and incomplete/unused support for pooling windows, which has been found to be unnecessary

[SERVICE-287] Prevent flicker on snap/tab previews when switching between valid/invalid targets

---

src/provider/workspaces/create.ts

Issue fixed by using the state from the DesktopWindow rather than the lower-level Window, which does not appear to give the correct result for state.
Restoring windows to the correct state appears to 'just work' now

[SERVICE-323] generateLayout has incorrect state for maximized windows

---

src/provider/APIHandler.ts
src/provider/main.ts
src/provider/model/DesktopEntity.ts
src/provider/model/DesktopModel.ts
src/provider/model/DesktopTabGroup.ts
src/provider/snapanddock/Resolver.ts
src/provider/snapanddock/SnapService.ts
src/provider/tabbing/TabService.ts
test/provider/deregisterConfig.test.ts
test/provider/deregisterWindow.test.ts
test/provider/dockingDisabled.test.ts
test/teardown.ts

Removed the previous (temporary) service-wide flags with the config mechanism.
The services that had toggle-able features now apply these feature flags on a per-window basis, so these features can be disabled for specific windows/apps without affecting any unrelated windows.

[SERVICE-305] Replace existing URL-based parameters with JSON config

---

src/client/types.ts
src/provider/tabbing/TabService.ts
src/provider/tabbing/components/ApplicationConfigManager.ts
test/demo/tabbing/createTabFromMultipleWindows.test.ts

We now store either the string "default", or the URL and tabstrip height if using a custom tabstrip.
Note that we now reuse ApplicationUIConfig in TabGroupInfo. We also have removed URL from TabGroupInfo  and tabGroupHeight in TabGroupDimensions as these are in ApplicationUIConfig

[SERVICE-334] Prevent embedding of absolute URL's to default tabstrips within saved workspaces	

---

test/demo/previewWindow.test.ts
test/provider/deregisterWindow.test.ts
test/teardown.ts

This fixes tests that broke due to reliance on the preview window having a particular name, which changed with SERVICE-287

[N/A] Fix previewWindow test break

---

src/provider/model/DesktopWindow.ts

Improved handling of intermediate failures inside transactions. This ensures that activeTransactions will always be updated, even if something inside errors.

[N/A] Fix failing nativeGroup tests

---

src/client/main.ts
src/client/tabbing.ts
src/provider/APIHandler.ts
src/provider/main.ts
src/provider/model/DesktopModel.ts

API stub was added as part of client API refactor, but was blocked by config feature not being merged.
API call has now been implemented on the provider side.

[N/A] Implemented register API

---

src/client/types.ts
src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts
src/provider/tabbing/TabService.ts
src/provider/workspaces/create.ts
src/provider/workspaces/restore.ts
src/provider/workspaces/utils.ts
test/demo/tabbing/createTabFromMultipleWindows.test.ts

The previous fix for SERVICE-323 only worked for currently running apps, as different codepaths were used for restoring the state of windows depending on if it was running or not.
The positionWindow method is now used for both the case where we're restoring an app that is already running, and when it needed to be started
This PR now also saves and restores state of the tab group itself, which causes a schema change that we want in before 1.0

[SERVICE-323] Restoring maximized state now works regardless of whether app was running or not

---

src/provider/model/DesktopTabGroup.ts
test/demo/tabbing/maximizeTabGroups.test.ts
test/provider/utils/assertions.ts

Fix/Mitigation for issue where maximising a snapped tabGroup could cause strange sizing/positioning of the snapped windows

[SERVICE-314] Undock tabGroups when maximising

---

src/provider/model/DesktopTabGroup.ts
test/demo/tabbing/tabGroupResizeConstraints.test.ts

Changed some of the constraints propagation logic to restrict resizing on the internal edge of a tabgroup.

[SERVICE-278] Prevent resizing of the top edge of a tabbed window

---

src/provider/APIHandler.ts
src/provider/model/DesktopTabGroup.ts
src/provider/workspaces/restore.ts
src/provider/workspaces/utils.ts

This still needs full testing, but would appreciate eyes on this.
There's four real parts to this
1. At the start and end of the restoreWorkspace method, mark and unmark that a restore is in progress, and if the restoreWorkspace  method is called again during a restore, throw an exception
2. Add a timeout when waiting for a  WorkspaceAPI.RESTORE_HANDLER call to the client app via sendToClient to return
3. Add a timeout when waiting for a client app to notify the provider that it is ready to restore
These 3 together /should/ be enough to ensure that we don't start a restore when we are already mid-restore but will also never block restores permanently due to a misbehaving client app. However, for caution, we also have:
4. A global timeout on the marker that restore is running, so that we …

[SERVICE-336] Clicking restore in the middle of another restore breaks restoration

---

src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts

Added some better failure handling to the low-level window grouping logic to prevent calling mergeGroups on windows which no longer exist.

[SERVICE-324] Restoring certain layout configurations twice causes runtime errors

---

src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts
src/provider/snapanddock/SnapService.ts
src/provider/tabbing/TabService.ts
src/provider/workspaces/utils.ts

Reduces the amount of calls we are making when performing various tabbing operations.  
One outstanding flicker remains when breaking up a tab group (2 tabs only).  This is caused by windows receiving focus when being taken from a frameless to framed state.

[SERVICE-316] Windows sometimes flicker when switching tabs

---

src/provider/model/DesktopWindow.ts

Work-around for runtime issue with resetting maxWidth/Height constraints. Prevents windows being non-maximizable after being tabbed, except in cases where one of those windows had max-size constraints.

[N/A] Prevent windows being non-maximizable after tabbing+un-tabbing

---

src/provider/model/DesktopTabGroup.ts
src/provider/tabbing/TabService.ts
test/demo/tabbing/tabGroupResizeConstraints.test.ts
test/demo/utils/tabServiceUtils.ts

- TabGroups will check their maximizability before maximising and throw an error if false.
- `updateGroupConstraints` will now also update the maximizability of the tabGroup.
- TabGroup maximizability is determined by the union of all windows' maximizability and whether they have any maximum height/width constraints.

[SERVICE-348][SERVICE-367] Block maximize actions on tabgroups that contain a window with maximizable: false or maxWidth/maxHeight constraints

---

src/provider/model/DesktopModel.ts
src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts
src/provider/snapanddock/utils/RectUtils.ts
src/provider/tabbing/TabService.ts
test/demo/tabbing/tabToMaximizedWindow.test.ts
test/demo/utils/tabServiceUtils.ts

Second run at this story.
- Added logic to the provider to store and track changes to the current monitor rectangles
- Changed `DesktopWindow.currentState` to return the apparent coordinates if a window is maximized (Note: only changed the public getter, the internal state is still the same).
- Also ended up fixing an issue where maximizing a tabGroup would always make it fill the monitor that the provider was on, regardless of the actual position of the tabGroup
- It is now not possible to tab to a window hidden underneath a maximized window. 
- Added a few new util functions to facilitate these changes
Known issues: 
- Currently, the tabstrip will still show the maximize icon when first tabbing to a maximized window. I have tested, and the model state is correct, it is just that the …

[SERVICE-352] Fix: Strange preview window positioning when tabbing to a maximized window

---

src/provider/tabbing/TabService.ts
test/demo/tabbing/tabGroupResizeConstraints.test.ts

I have updated the constraints compatibility check when tabbing to account for the fact that windows can shrink when tabbing. This will also prevent tabbing if windows are too small to reasonably be resized to accommodate the Tabstrip.
This PR is primarily a mitigation rather than a full solution. We should revisit down the road to see if we can move the window instead of resizing in these cases.

[SERVICE-353] Strange window positioning if tabbed windows are shorter than the tabstrip

---

src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts
test/demo/tabbing/tabGroupResizeConstraints.test.ts

Root cause of issue was found to be using stale position from currentState. This PR adds some mitigations including 
- slight delay in addTabInternal to allow bounds-changing events to be processed in the middle
- Added readonly public boolean to DesktopWindow which tracks if the window is moving (set in bounds-changing and unset in bounds-changed).
- Added logic to addTabInternal which will detect if the target window is moving and delay most of the adding operation until the movement has stopped (i.e. the onCommit signal is fired).

[SERVICE-360] Possible to disjoint tabs from tabstrips with quick mouse movements during addTab

---

src/provider/model/DesktopTabGroup.ts

This fixes an issue encountered on a similar path to SERVICE-354.
To reproduce the issue, create a tab group of two tabs, and then snap to an untabbed window. Then, call createTabGroupWithTabs for one of the tabbed windows, and the untabbed window. This would result in a tabstrip that was offset from any windowed.
This also adds an await to setSnapGroup in the edited function, out of caution.

[SERVICE-354] Calling 'createTabGroup' from a tabbed window causes other windows in the tab group to be ejected to the wrong positions (Partial fix)

---

src/provider/model/DesktopTabGroup.ts
src/provider/workspaces/restore.ts

- Reverse ordering of parent and child `removeTab` calls. Before, all parent apps would `removeTab` before all children would. This timing would allow the children to attach to its neighbors on TabGroup disbanding. 
- Fix non-showing tabs on restore.
- Lint.

[SERVICE-350] Prevent child windows from snapping to other windows during restoration

---

src/provider/model/DesktopTabGroup.ts
test/demo/tabbing/tabGroupResizeConstraints.test.ts

DesktopTabGroup listens for teardown of tabstrip window and closes all tabs as needed
Passed Jenkins at d5060e5

[SERVICE-358] Possible to close a tabstrip independent of its tabs

---

.gitmodules
package.json

Added the [redesigned typedoc template](https://github.com/openfin/typedoc-template) as a submodule and made typedoc use it when generating API docs.

Add typedoc theme as a submodule & use it in typedoc

---

src/provider/model/DesktopModel.ts
src/provider/model/ZIndexer.ts
test/demo/workspaces/formerTabGroupRestoreResize.test.ts
test/provider/tabOnDragOver.test.ts

The model's `getWindowAt` method will no longer return windows that are covered by a de-registered window
This was achieved by using the `ZIndexer` to perform the actual check (since it also tracks non-registered windows), which required having the `ZIndexer` also log the bounds of a window. No extra events were required to do this, instead the util stores the bounds data that comes from the `bounds-changed` events.
Only `bounds-changed` events are used for the position tracking, meaning that data for any window currently being moved will be stale. In actual usage, any active window is always excluded from the `getWindowAt` check.

[SERVICE-357] Prevented tabbing "through" de-registered windows.

---

src/fin.d.ts
src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts
src/provider/tabbing/TabService.ts
test/provider/tabOnDragOver.test.ts

Using `getInfo()` to fetch document title from each window. This isn't always immediately available, so service will re-request the window title when tabbing, if the title isn't already known.
It seems the API returns the URL of the page in cases where there is no `<title>` tag in the DOM. The service will detect these cases, and use the window name instead (as per earlier behaviour).

[SERVICE-373] Tab properties now initialised with window title

---

src/provider/model/DesktopWindow.ts
test/demo/snapanddock/validateGroup.test.ts

This was accomplished by adding a call to `snapGroup.validate()` in the maximize event callback on `DesktopWindow`s. Since we now track the visually apparent bounds of maximised windows, the service will recognise that the group is no longer contiguous and take the appropriate actions (e.g. undocking windows or splitting the group).
I expect that this is still some very small time windows where moving the maximized window could cause issues. This is pretty much unavoidable as we are only able to react to the event, not intercept it mid-flight. I have not been able to reproduce this myself, so I expect the window is small enough to not be a major problem.

[SERVICE-375] Undock docked windows when maximizing

---

src/provider/model/DesktopModel.ts
src/provider/model/ZIndexer.ts

This resolves a test failure caused by ZIndexer not responding to windows being hidden, and so believing hidden windows to be obscuring the expected active window.
Jenkins succeeded at a9d0349.

[SERVICE-357-fix] Update ZIndexer to track 'active' state of windows 

---

src/provider/utils/error.ts

Error window was being pointed to a non-existent file when running off of the cdn. Fixed the relative path calculation to actually make sense for setups other than the local demo.

[N/A] Fix bad path logic in error window creation

---

Jenkinsfile

Have changed the location the generated docs are deployed to as part of the build process.
Now deployed to `/docs/services/layouts/<version>`, as per other projects. Docs folder is still sub-divided into `api` and `config`.

[N/A] Moved API/config doc location when deploying to the CDN

---

src/provider/workspaces/create.ts
src/provider/workspaces/restore.ts

Obviously all apps registered with layouts should be good S&R citizens, but this handles a case I ran into with Trade Blotter where it isn't.
Open to these being deemed unnecessary and we instead place a strong requirement on apps to Do The Right Thing.
Jenkins in progress at  e003775

[N/A] Track which apps have made a call to appReadyForRestore, as a heuristic for which apps are good S&R citizens

---

res/provider/app.json

This restores @MichaelMCoates original mitigation for restore failures when restoring many manifest apps, which is the low risk fix for 1.0.
> When restoring a large workspace that uses many applications created from manifest, the core/RVM don't currently account for that level of load. If application launches hang a bit long, they timeout silently, which breaks restoration. Setting this timeout extends the amount of time before the timeout fails, until we have a more permanent solution.
Succeeded on Jenkins.

[N/A] Set message-timeout to 60 seconds for createFromManifest lag

---

package.json
src/client/internal.ts
src/client/main.ts
src/client/snapanddock.ts
src/client/tabbing.ts
src/provider/APIHandler.ts
test/client/TabApi.unittest.ts
test/client/TabGroupActions.unittest.ts
test/client/TabStripApi.unittest.ts
test/client/utils/ErrorMsgs.ts

- Added some additional checks to the `parseIdentity` checks, specifically around the types of the arguments provided.
- Made a new `parseIdentityRule` method which does a similar thing but for identities allowing Regex.
Note: I've also included a fix for an error I encountered during this story where the undock methods weren't properly returning provider-side errors to the client.

[SERVICE-359] Improve input guards on client methods

---

src/client/connection.ts
src/client/main.ts
src/client/snapanddock.ts
src/client/tabbing.ts
src/client/tabstrip.ts
src/client/workspaces.ts
src/demo/normalApp.ts
src/demo/testbed/App.ts
src/demo/testbed/EventsUI.ts
src/provider/APIMessages.ts
src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts
src/provider/tabbing/TabService.ts
src/provider/workspaces/create.ts
src/provider/workspaces/utils.ts
test/demo/utils/workspacesUtils.ts
test/demo/workspaces/schemaVersion.test.ts

Updated workspaces API docs, and some minor tweaks/clean-up elsewhere.
Some code changes to clean-up `Workspace`/`WorkspaceWindow`, and to get the service to stick to those definitions (removed some unused fields that were being added to these objects during generate calls).

[SERVICE-328, SERVICE-377] Updated API docs, removed need for v1 types within client

---

src/provider/model/ZIndexer.ts
test/demo/tabbing/tabGroupResizeConstraints.test.ts
test/demo/tabbing/tabToMaximizedWindow.test.ts
test/demo/utils/AppInitializer.ts
test/demo/workspaces/formerTabGroupRestoreResize.test.ts
test/demo/workspaces/snapSaveAndRestore.test.ts
test/demo/workspaces/tabSaveAndRestore.test.ts
test/provider/utils/tabWindowsTogether.ts

This partially addresses SERVICE-380, but does leave some so-far unexplained random test failures remaining.
Many of the random test failures were caused by `tabWindowsTogether` not resulting in windows being tabbed together, which was ultimately caused by `ZIndexer` occasionally not properly tracking an OF window.
I also saw some cases locally where the topmost window in the stack would be the preview window, which seemed to be another cause of test failures, but I've been unable to confirm this occured on Jenkins.
This PR
- Adds logging to `tabWindowsTogether` so we can track when it does not work as expected. That is complicated by the fact that occasionally we do not expect `tabWindowsTogether` to actually tab windows together
- Changes `ZIndexer` to add windows to the stack ASAP upon …

[N/A] Modify ZIndexer to reduce test failure rate

---

res/demo/testbed/index.html
scripts/server/spawn.js
src/demo/spawn.ts
src/demo/testbed/View.ts
src/demo/testbed/WindowsUI.ts
src/provider/model/DesktopWindow.ts

The PR incorporates @MichaelMCoates's changes to make it easier to bring up a maximized app.
The bug is fixed by having DesktopWindow.getWindowState() call window.getState(), rather than relying on window.getOptions().state, which seems to give stale data

[SERVICE-383] Tabbing to a window with a declared state of 'maximized' in its app.json will end up maximizing the TabSet

---

Jenkinsfile

Skips robotjs install, since the VM this runs on isn't setup with the robotjs dependencies.

[N/A] Fix for error when running unit tests on CI

---

src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts

Original bug was calling `bringToFront` on windows that do not exist, which threw the error `bringToFront is not a function`. The bug was caused by reattachment of a DesktopWindow that doesn't exist (when closing out a TabSet that is snapped to other windows).
I added a check to the reattachment code to only attach the DesktopWindow if it is `ready`. Is that the most dependable call to know if a window exists? Would we be better served adding the `ready` check in `setSnapGroup` instead?
Same goes for the `bringToFront` check. Should we use the `ready` check there instead?

[SERVICE-384] Prevent reattachment of a DesktopWindow that no longer exists

---

src/provider/main.ts

Quick PR. Let me know if this should be more expansive/we should reject with a different message.

[SERVICE-413] Have calls to the client API reject when the service is in "unsupported environment" mode

---

src/client/connection.ts
src/client/workspaces.ts

Phil's implementation. After a lot of messing around, couldn't figure out a way to optimize it further. 
Essentially fetches the channel client from a function instead of an awaited promise.

[SERVICE-401] Fix "unhandled promise rejection" errors when including client from non-OpenFin contexts

---

src/provider/main.ts

Disabling user-visible message when running in non-100% display scaling ratios. Instead, error is messaged to debug console of clients that connect to the service.

[N/A] Disabling display scaling error message

---

README.md
res/demo/libScriptIncluded.html
webpack.config.js

Renamed from `OpenFinLayouts` global variable to `layouts`.
This is to align with the same change made in FDC3, and to make this version of the client less clunky to use.
See https://github.com/HadoukenIO/fdc3-service/pull/30.

[SERVICE-423] Renamed global variable created by non-module client

---

src/provider/model/DesktopModel.ts
src/provider/model/DesktopSnapGroup.ts
src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts
src/provider/snapanddock/Constants.ts

- Expose 'displayScaling' boolean from DesktopModel, so we can use DS mitigations selectively
- Manually compute the transform type when display scaling is active
- Disable resize constraints when a window is being dragged, so prevent window-growth bug

[SERVICE-447]/[SERVICE-449] Unable to tab windows/Windows in snap group with resize constraints grow rapidly when dragged

---

src/provider/model/DesktopWindow.ts

Added some additional logic to handle focused to stop the "keep tab group at same z-index" stuff being blocked when the group is maximized.

[SERVICE-451] Fix tab group splicing when maximized

---

src/provider/model/DesktopWindow.ts
src/provider/utils/iteration.ts

Previously, when we used `applyOverride()` and `resetOverride()` on `DesktopWindow`, the store value to reset to would get lost if there was a call to `refresh()` between the apply and reset steps. I ran into this problem in the display scaling feature branch, as we call can `refresh()` around the same time we make a window translucent for snapping.
This was because when calling `updateState()` with `ActionOrigin.SERVICE_TEMPORARY`, we were not properly updating `this._modifiedState` as we were for `ActionOrigin.SERVICE`. This fix changes it so that we properly update `this._modifiedState` for both `ActionOrigin.SERVICE` and `ActionOrigin.SERVICE_TEMPORARY`.

[N/A] Track changes when using ActionOrigin.SERVICE_TEMPORARY

---

src/provider/model/DesktopWindow.ts

Fix maths being back-to-front, causing us to detect resizes as moves

[SERVICE-449][Continued] Windows in snap group with resize constraints grow rapidly when dragged

---

src/provider/main.ts
src/provider/model/DesktopModel.ts
src/provider/model/DesktopSnapGroup.ts
src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts
src/provider/snapanddock/Constants.ts

This enables support for display scaling at 150% and 200%, and includes mitigations for issues that occur at this scales
Misreporting of moves vs. resizes, so we compute this ourselves
Grouped windows resizing when being moved when some of the group includes resize constraints, so we temporarily resize constraints during moves
Fuzziness when checking group validity, since windows drift slightly when being moved, and don't always go quite where we want them to when they are first snapped

[SERVICE-435] Display scaling support for 150% and 200%

---

Jenkinsfile

Bad s3 syntax and missing `env.` when referencing a variable

[N/A] Fix Jenkinsfile deploy step

---

src/client/internal.ts
src/client/snapanddock.ts
src/demo/testbed/SnapAndDockUI.ts
src/demo/testbed/TabbingUI.ts
src/provider/APIHandler.ts
test/demo/snapanddock/getDockGroup.inttest.ts

Added a new client api method, `getDockedWindows` (name definitely up for discussion), which will return the identities of all entities in the same docked group as the target window. 
This was added to address a use-case where a window uses the docked events to update some ui element, but if refreshed has no easy way to know which state to put itself in.
I have also added some logic to the testbed apps which should make them behave properly if reloaded while docked.

[SERVICE-454] Add API for querying docked status

---

package-lock.json
src/provider/model/DesktopTabGroup.ts
src/provider/model/DesktopWindow.ts

Certain bounds-changed events will now trigger a group validate. This will ensure that if a window is moved by through the context menu move it will get properly ejected from the group.
This is intended as a temporary workaround on the layouts side until a full solution is found from the runtime/core side

[SERVICE-472] Add special validation check for right-click-moves

---

src/provider/model/DesktopWindow.ts
src/provider/snapanddock/Resolver.ts
test/demo/utils/createWindowsWithConfig.ts

Fixed flicker issue with fully-transparent previews, fixed uuid issue when running both snap and tab preview tests in the same run.

[SERVICE-471] Fixed flicker issue with fully-transparent previews

---

Jenkinsfile

Upload of `app.runtime-*.json` manifests wasn't working due to missing `aws` argument.

[N/A] Fixing runtime channel manifests upload

---

test/demo/utils/createWindowsWithConfig.ts

Adds `provider: testing` to this util to avoid duplicate UUID error popups

[NA] Fix createWindowsWithConfig

---

src/provider/model/DesktopTabstripFactory.ts
src/provider/tabbing/DragWindowManager.ts

Stops `DragWindowManager` & `DesktopTabstripFactory` windows flickering on service startup.
Also fixes tabstrip pooling. Before tabstrips pooling was async and overwriting the pool array, leaving windows that were not being managed.
#414 Removes the flicker from preview windows.

[NA] Prevent window flicker on service startup

---

src/provider/workspaces/restore.ts

This PR uses `startManyManifests` to start a batch of applications, instead of running them individually. This avoids the issue reported earlier of applications failing to come up during a large restore.
This PR is linked to the following PRs:
https://github.com/HadoukenIO/core/pull/907
https://github.com/HadoukenIO/js-adapter/pull/325
https://github.com/openfin/openfinrvm/pull/307

[RUN-5434]/[RUN-5435] Change restore to use startManyManifests
